#! /bin/sh

APP_NAME1="\"ACME Online Bookstore Application\""
APP_ID1=2
PVN_ALERT_TIME1="\"Tue Apr 17 14:02:55 PDT 2012\""
PRIORITY1=1
SEVERITY1="\"ERROR\""
TAG1="\"Response time policy violation\""
RULE_NAME1="\"Business Transaction response time is much higher than normal\""
RULE_ID1=8
PVN_TIME_PERIOD_IN_MINUTES1=5
PVN_AFFECTED_ENTITY_TYPE1="\"BUSINESS_TRANSACTION\""
PVN_AFFECTED_ENTITY_NAME1="\"ViewCart.addToCart\""
PVN_AFFECTED_ENTITY_ID1=86
PVN_NUMBER_OF_EVALUATION_ENTITIES1=1
PVN_EVALUATION_ENTITY_TYPE_11="\"APPLICATION_COMPONENT_NODE\""
PVN_EVALUATION_ENTITY_NAME_11="\"Node_8000\""
PVN_EVALUATION_ENTITY_ID_11=2
NUMBER_OF_TRIGGERED_CONDITIONS_11=1
SCOPE_TYPE_11="\"APPLICATION_COMPONENT_NODE\""
SCOPE_NAME_11="\"Node_8000\""
SCOPE_ID_11=2
PVN_TC_CONDITION_NAME_11="\"Average Response Time (ms) Baseline Condition\""
PVN_TC_CONDITION_ID_11=77
OPERATOR_11="\"GREATER_THAN\""
CONDITION_UNIT_TYPE_11="\"BASELINE_STANDARD_DEVIATION\""
USE_DEFAULT_BASELINE1="\"true\""
THRESHOLD_VALUE_11=5
OBSERVED_VALUE_11=6
SUMMARY_MESSAGE1="\"Business Transaction response time is much higher than normal triggered at Tue Apr 17 14:02:55 PDT 2012. This policy was violated because the following set itions were met for the ViewCart.addToCart Business Transaction for the last 5 minute(s):   For Evaluation Entity: Node_8003 Node  For Evaluation Entity: Node_8000 Node - Average Response Time (ms) Baseline Condition is greater than 5. Observed value = 6 - Calls per Minute Condition is greater than 50. Observed value = 940\""
INCIDENT_ID1=2
DEEP_LINK_URL1="\"http://WIN-FKL67IRSIPI:8090//#location=APP_INCIDENT_DETAIL&incident=\""
EVENT_TYPE1="\"POLICY_OPEN_CRITICAL\""
ACCOUNT_NAME1="\"hello\""
ACCOUNT_ID1="\"asdf23ewe3\""

. ./appd_alert.sh "${APP_NAME1}" "${APP_ID1}" "${PVN_ALERT_TIME1}" "${PRIORITY1}" "${SEVERITY1}" "${TAG1}" "${RULE_NAME1}" "${RULE_ID1}" "${PVN_TIME_PERIOD_IN_MINUTES1}" "${PVN_AFFECTED_ENTITY_TYPE1}" "${PVN_AFFECTED_ENTITY_NAME1}" "${PVN_AFFECTED_ENTITY_ID1}" "${PVN_NUMBER_OF_EVALUATION_ENTITIES1}" "${PVN_EVALUATION_ENTITY_TYPE_11}"  "${PVN_EVALUATION_ENTITY_NAME_11}" "${PVN_EVALUATION_ENTITY_ID_11}" "${NUMBER_OF_TRIGGERED_CONDITIONS_11}" "${SCOPE_TYPE_11}" "${SCOPE_NAME_11}" "${SCOPE_ID_11}"  "${PVN_TC_CONDITION_NAME_11}" "${PVN_TC_CONDITION_ID_11}"  "${OPERATOR_11}" "${CONDITION_UNIT_TYPE_11}" "${USE_DEFAULT_BASELINE1}" "${THRESHOLD_VALUE_11}" "${OBSERVED_VALUE_11}" "${SUMMARY_MESSAGE1}" "${INCIDENT_ID1}" "${DEEP_LINK_URL1}" "${EVENT_TYPE1}" "${ACCOUNT_NAME1}" "${ACCOUNT_ID1}"


echo ${EVENT_DETAIL}
echo ${SUMMARY_MESSAGE}